server:
  port: 8070
info:
  app:
    name: myApp
    version: '0.1'
    grailsVersion: 6.1.0
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
  gorm:
    reactor:
      events: false
dataSource:
  url: jdbc:mysql://localhost:3306/demo
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: Kavita@123
  pooled: true
  jmxExport: true
  dialect: org.hibernate.dialect.MySQL8Dialect
  dbCreate: update

hibernate:
  showSql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
